language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - "python setup.py install"
 - "pip install --use-mirrors 'WebTest>=1.4.3' nose==1.3.0 pep8==1.4.5 wdb==0.9.3"
script:
 - "pep8 --statistics rororo/"
 - "nosetests -w rororo/"
 - "nosetests -w examples/explorer/"
 - "nosetests -w examples/star_wars/"
