language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - "python setup.py install"
 - "pip install --use-mirrors WebTest>=1.4.3 pep8==1.4.5 unittest2==0.5.1 wdb==0.9.3"
script:
 - "pep8 --statistics rororo/"
 - "unit2 discover -s rororo/"
 - "unit2 discover -s examples/explorer/"
 - "unit2 discover -s examples/star_wars/"
