version: 2
jobs:
  lint:
    docker: &py37
      - image: playpauseandstop/docker-python:1.0.3
    steps:
      - checkout
      - run: make lint
  test37:
    docker: *py37
    steps:
      - checkout
      - run: TOXENV=py37 make test
      - run: make coveralls
  deploy:
    docker: *py37
    steps:
      - checkout
      - run: make install deploy
workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters: &all_tags_and_branches
            tags:
              only: /.*/
      - test37:
          requires:
            - lint
          filters: *all_tags_and_branches
      - deploy:
          requires:
            - test37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
