version: 2
jobs:
  lint:
    docker: &py37
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: &install_bootstrapper
          name: Install bootstrapper
          command: pip install --user bootstrapper
      - run: &update_path
          name: Update path
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run: make lint
  test35:
    docker:
      - image: circleci/python:3.5.5
    steps:
      - checkout
      - run: &install_locales
          name: Install locales
          command: sudo apt-get install -y locales locales-all
      - run: *install_bootstrapper
      - run: *update_path
      - run: TOXENV=py35 make test
      - store_test_results:
          path: test-results/nosetests/
      - run: "[ -r nosetests.xml ] && mv nosetests.xml test-results/nosetests/results.xml || :"
  test36:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: *install_locales
      - run: *install_bootstrapper
      - run: *update_path
      - run: TOXENV=py36 make test
      - store_test_results:
          path: test-results/nosetests/
      - run: "[ -r nosetests.xml ] && mv nosetests.xml test-results/nosetests/results.xml || :"
  test37:
    docker: *py37
    steps:
      - checkout
      - run: *install_locales
      - run: *install_bootstrapper
      - run: *update_path
      - run: TOXENV=py37 make test
      - run: make coveralls
      - store_test_results:
          path: test-results/nosetests/
      - run: "[ -r nosetests.xml ] && mv nosetests.xml test-results/nosetests/results.xml || :"
  deploy:
    docker: *py37
    steps:
      - checkout
      - run: *install_bootstrapper
      - run: *update_path
      - run: make deploy
workflows:
  version: 2
  ci:
    jobs:
      - lint
          filters:
            tags:
              only: /.*/
      - test35:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - test36:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - test37:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test35
            - test36
            - test37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
